# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_foto', models.CharField(blank=True, default='Sin título', max_length=40, null=True)),
                ('foto', models.ImageField(upload_to='Fotos/')),
                ('fecha_pub', models.DateField(auto_now_add=True)),
                ('favoritos', models.BooleanField(default=True)),
                ('comentario', models.CharField(blank=True, max_length=140, null=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Album.Categoria')),
            ],
        ),
    ]
